Update patch set 14
Patch Set 14: Code-Review-1

Hi Michael,

Saving CM and fault to the Elasticsearch database works fine (using Jakarta configuration), but when I tried to save cm and fault to MariaDB with Jakarta configuration I got an error: 

For CM:
"RestconfImpl|org.opendaylight.netconf.restconf-nb-bierman02 - 1.13.2 |Execution RpcError:
java.util.concurrent.ExecutionException: org.opendaylight.mdsal.dom.api.DOMRpcImplementationNotAvailableException: No implementation of RPC (urn:opendaylight:params:xml:ns:yang:devicemanager?revision=2019-01-09)push-cm-notification available
Caused by: org.opendaylight.mdsal.dom.api.DOMRpcImplementationNotAvailableException: No implementation of RPC (urn:opendaylight:params:xml:ns:yang:devicemanager?revision=2019-01-09))push-cm-notification available"

For fault:
"RestconfImpl|org.opendaylight.netconf.restconf-nb-bierman02 - 1.13.2 |Execution RpcError:
java.util.concurrent.ExecutionException: org.opendaylight.mdsal.dom.api.DOMRpcImplementationNotAvailableException: No implementation of RPC (urn:opendaylight:params:xml:ns:yang:devicemanager?revision=2019-01-09)push-fault-notification available
Caused by: org.opendaylight.mdsal.dom.api.DOMRpcImplementationNotAvailableException: No implementation of RPC (urn:opendaylight:params:xml:ns:yang:devicemanager?revision=2019-01-09))push-fault-notification available"

Patch-set: 14
Reviewer: Gerrit User 7843 <7843@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1