Update patch set 15
Patch Set 15: Code-Review-1

Hi Michael,

Thank you for the new patch set. Writing CM to mariadb database seems to work ok, but when I tried to save fault to MariaDB with Jakarta configuration I got an error: 

WARN  | qtp1609616541-1090 | SqlDBReaderWriter| 212 - org.onap.ccsdk.features.sdnr.wt.sdnr-wt-data-provider-dblib | problem writing data into db:
java.sql.SQLIntegrityConstraintViolationException: (conn=56) Cannot add or update a child row: a foreign key constraint fails (`sdnrdb`.`faultlog-v7`, CONSTRAINT `faultlog-v7_ibfk_1` FOREIGN KEY
(`controller-id`) REFERENCES `controller-v7` (`id`))
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Cannot add or update a child row: a foreign key constraint fails (`sdnrdb`.`faultlog-v7`, CONSTRAINT `faultlog-v7_ibfk_1` 
FOREIGN KEY (`controller-id`) REFERENCES `controller-v7` (`id`))

I also got an error:

WARN  | qtp1609616541-1090 | SqlDBClient| 212 - org.onap.ccsdk.features.sdnr.wt.sdnr-wt-data-provider-dblib - 1.3.0.SNAPSHOT | 
problem reading db for query 'SELECT * FROM `maintenancemode-v6` WHERE (`node-id`='VES') AND (`controller-id`='f9bd1934-d128-493e-9324-2fd6fdcf18a6') LIMIT 0,30;':
Caused by: java.sql.SQLException: Table 'sdnrdb.maintenancemode-v6' doesn't exist

I got the same error for tables: 'sdnrdb.controller-v6', 'sdnrdb.mediator-server-v6'
Probably somewhere in the project is still set a -v6 version for MariaDB.

Patch-set: 15
Reviewer: Gerrit User 7843 <7843@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1