Update patch set 1
Patch Set 1:

> Patch Set 1: Verified-1
> 
> Build Failed 
> 
> https://jenkins.onap.org/job/ccsdk-features-maven-verify-master-mvn36-openjdk11/293/ : FAILURE
> 
> Build failed to find artifact org.onap.ccsdk.parent:binding-parent:pom:2.2.0-SNAPSHOT needed for sub-project org.onap.ccsdk.features.sdnr.northbound:oofpcipoc-provider:bundle:1.2.2-SNAPSHOT: Failed to collect dependencies at org.onap.ccsdk.sli.core:sli-common:jar:1.3.0-SNAPSHOT: Failed to read artifact descriptor for org.onap.ccsdk.sli.core:sli-common:jar:1.3.0-SNAPSHOT. Check correct groupId, artifactId and version. This may also indicate a problem with nexus. Another possibility is that this is a -SNAPSHOT version and it has expired from nexus -- in that case check with the project which provides the artifact. ( https://jenkins.onap.org/job/ccsdk-features-maven-verify-master-mvn36-openjdk11/293/ )
> 
> Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/ccsdk-features-maven-verify-master-mvn36-openjdk11/293

On newer parent version (2.2.1-SNAPSHOT instead of 2.2.0-SNAPSHOT) there is simmilar issue:
java.io.IOException: Error resolving artifact org.onap.ccsdk.sli.core:ccsdk-sli:xml:features:1.3.2-SNAPSHOT: [Could not find artifact org.onap.ccsdk.sli.core:ccsdk-sli:xml:features:1.3.2-SNAPSHOT]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803) [bundleFile:?]
Caused by: java.io.IOException: Error resolving artifact org.onap.ccsdk.sli.core:ccsdk-sli:xml:features:1.3.2-SNAPSHOT: [Could not find artifact org.onap.ccsdk.sli.core:ccsdk-sli:xml:features:1.3.2-SNAPSHOT]

Patch-set: 1